### PR TITLE
Update sensor.py to round numbers

### PR DESCRIPTION
**Pull request by duddi**
Round sensor value, no more need for templates for rounding.

### CODE REVIEW

**Comment by duddi** [comment]
Change, set sensor to 0, when startup, no more fails in log.

**Comment by dingusdk** [comment]
Thanks for the PR - this not really needed anymore, because HA now has a "Display precision" in the UI. It is also better to have the rounding in the UI that in the actual data, and it is customizable to each user can have his preferences.

**Comment by duddi** [comment]
Custom UI dont have display precision, It is also not necessary to have such a high decimal point as the controller does not work with more than 2, and the accuracy of this value is around +/- 1 integer.

Just my 2 cents :)

**Comment by dingusdk** [comment]
You made this PR from your master branch - so every change you make to your master goes into this PR, so I will close this PR.

I keep the code in this repository a copy of the PR I have for the official HA, to make sure it is tested and ok. I am still waiting for it to be merged, (about to give up!) I will prefer to not make make more changes until it is merged, because that will just delay it even more. 

P.S. the sensors are not just decimal numbers, it can also be an integer or time/date, currently you assume it is always decimal numbers. 
It is fine you keep your work in your own repository, once my PR is merged I will include the rounding of decimals in the official integration.

**Pull request closed without merging**
